create database Jntu;
use Jntu;
create table students(id varchar(255), names char(35), course char(30));
select * from students;
create table courses(courseid varchar(255), branch char(30));
insert into courses values("CCO1", "CSE"), ("CCO2", "MSE"), ("CCO3", "EEE"), ("CCO4", "ECE"), ("CCO5", "CIV"), ("CCO6", "ME");
select * from courses;
alter table courses add proffessor varchar(255);
select * from courses;
alter table courses drop proffessor;
select * from courses;
alter table courses modify branch varchar(255);
select * from courses;
alter table courses rename column branch to course;
select * from courses;
alter table courses add column credits int(10);
select * from courses;
alter table courses modify column credits varchar(255);
select * from courses;
alter table courses rename column course to subject;
select * from courses;
insert into students values("a101", "shiva", "eie"), ("a102", "shankar", "ece"), ("a103", "pavan", "civ"), ("a104", "reddy", "eee"), ("a105", "katam", "it"), ("a106", "chotu", "cse");
select * from students;
alter table students add column fee int(200);
select * from students;
insert into students (fee) values(2400), (3000), (3500), (4599), (3900), (4200);
select * from students;
update students set fee = 2400 where fee is null;
select * from students where fee is null;